### ISSUE TITLE
Is this still alive/functional

### ISSUE THREAD

**Issue by ulquiorra-dev** [JayFoxRox/xbe-loader#11]
Hello JayFoxRay,

I have found this [Reddit](https://www.reddit.com/r/originalxbox/comments/9wki8p/smb_to_xbox_games/) discussion that leads me to this repo.

I would like to know if any advances have been made since the reddit post or if this is somehow functional.

Also, I would like to know how much effort you think this will need to make it functional.

I will be happy to help. I am not an nxdk specialist actually, but I have made some ports of 2d games for WiiU in the past so with your guidance maybe I could contribute

**Comment by JayFoxRox** [comment]
> I would like to know if any advances have been made since the reddit post or if this is somehow functional.

I don't remember. Check the commit dates?

I certainly don't work on it anymore at the moment, and I don't have plans to continue working on it (as I've mostly stopped work on the original Xbox).

> Also, I would like to know how much effort you think this will need to make it functional.

I've successfully used this (or a variation of it) to run at least one game (Smashing Drive) via network (at horrible speeds & ending in a crash if I remember, possibly #7).
I probably used this http server (as indicated by my activity): https://github.com/danvk/RangeHTTPServer/issues/20#issuecomment-1458490906

I believe @dracc tried running xbe-loader and couldn't make it work.
However, I still think it should work out of the box, or with minimal changes, such as the target host:

https://github.com/JayFoxRox/xbe-loader/blob/13919c8e65b8934828a4d4ddb12b49c423ed66cc/http_client.c#L95

It should come from here:

https://github.com/JayFoxRox/xbe-loader/blob/13919c8e65b8934828a4d4ddb12b49c423ed66cc/xiso_driver.c#L41-L43

but I have conflicting options in a couple of places and hardcoded things at varying stages during development (as I first tested the XISO driver by serving local files instead of doing network fetches). Also see:

https://github.com/JayFoxRox/xbe-loader/blob/13919c8e65b8934828a4d4ddb12b49c423ed66cc/main.c#L976-L978

I believe the most desperately needed feature is proper NIC emulation, so the game networking code and the network client can co-exist (see issue #5). Also games which use quick-reboots to switch XBEs will obviously fail - instead of loading into the game XBE, we'd have to boot into xbe-loader again (with new parameters for the new target), see #4.
The performance was largely hindered by the poor nxdk network driver (which has since been reworked, so it should be a non-issue now, see #6 and https://github.com/XboxDev/nxdk/pull/611). Aside from that, there's probably a lot of broken stuff in the filesystem driver interface and the implementation, like this (see issue #1):
https://github.com/JayFoxRox/xbe-loader/blob/13919c8e65b8934828a4d4ddb12b49c423ed66cc/xiso_driver.c#L559-L561

As you can see, most problems have corresponding GitHub issues and the code is (for the most part) pretty simple.
I think in addition to #2, a focus should be to make xbe-loader more re-usable, because the foundation of it could be used to create something like a DXT loader / trainer loader or generally something to debug applications.

I had also prototyped an ingame overlay with https://github.com/JayFoxRox/xbox-fps-overlay and my idea has always been to turn xbe-loader into an ingame menu where you can toggle development tools, trainers, take screenshots, view performanc profiles, etc.

> I will be happy to help. I am not an nxdk specialist actually, but I have made some ports of 2d games for WiiU in the past so with your guidance maybe I could contribute

It isn't so much about nxdk or game development. This is a Windows kernel filesystem driver and some lwip networking stuff, with some Xbox specific kernel stuff.
However, any capable C coder should be able to work on it (some reverse engineering and x86 knowledge might be necessary).
If a PR lands I might merge it, but you can also fork this and keep working on it yourself.
I'm unsure about the license though - I believe it's all my code, but I'd like to remain in control, because this code could be misused easily. I'll reconsider the license if someone actually works on it - it shouldn't be a blocker.

I assume the people on XboxDev Discord could give some guidance (I'm not there anymore though and don't have time to provide guidance either).

---

I'll close this issue, because it's not an actual issue or task that can be solved (other than answering it, which I did).
I'll still respond if there are any questions left.

**Comment by ulquiorra-dev** [comment]
Hey, thanks for your great answer. if I get anything good I will do an MR
